### ISSUE TITLE
more structured 

### ISSUE THREAD

**Issue by kushayb** [vikram-kangotra/Proto-rust#1]
https://github.com/vikram-kangotra/Proto-rust/blob/0c94d1ef384da06fa3bf189e35ba74530b255148/src/parser.rs#L19C3-L19C3
why dont u use `Peekable<T>` for peeking the items , that way u don`t have to make a new `peek` function

**Comment by kushayb** [comment]
https://domenicquirl.github.io/blog/parsing-basics/
see this ...

**Comment by vikram-kangotra** [comment]
> https://github.com/vikram-kangotra/Proto-rust/blob/0c94d1ef384da06fa3bf189e35ba74530b255148/src/parser.rs#L19C3-L19C3 why dont u use `Peekable<T>` for peeking the items , that way u don`t have to make a new `peek` function

Back when I was working on this toy project, I had just started learning rust and most of the code is just direct rewrite of the language that I had written in C. These days I'm occupied with something else and I wish to continue this project some day. And I will surely use `Peekable<T>` then. Thanks for the suggestion :smile:

**Comment by kushayb** [comment]
man , i had a query could you respond to my linked in request , i wanted to ask some questions

**Comment by vikram-kangotra** [comment]
yeah sure, I'll be happy to help :smile: 
Send a message to me on linkedIn. What's your linkedIn ID?

**Comment by kushayb** [comment]
astro
